### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by Shubhamrawat5** [rsumit123/ipl_live#1]
Both apis are down as It was hosted on Heroku, Can you rehost the apis in some other website like koyeb, railway, cyclic, etc or vercel with serverless function

**Comment by rsumit123** [comment]
Hi @Shubhamrawat5 , Thanks for pointing this out. This was previously hosted on heroku free dynos, and since heroku has cancelled them, they would be down too. I will move this API to a different service soon and let you know.

**Comment by Shubhamrawat5** [comment]
Yes please, actually I was using your api for my whatsapp bot, which posts cricket updates in groups.

**Comment by rsumit123** [comment]
@Shubhamrawat5 Nice, great idea. Will try to update these asap. Hopefully by tomorrow.

**Comment by Shubhamrawat5** [comment]
Is it fixed?

**Comment by rsumit123** [comment]
Hey @Shubhamrawat5 , The API is live but it is taking some time to set a custom domain name and someDNS records. Meanwhile I am sharing a temporary url with you. Please use this url temporarily as it will be updated (replaced) with a permanent one shortly. Will let you know and update the README, when its done. 

Here is the temporary url: https://vw4twun40j.execute-api.us-east-1.amazonaws.com/dev that you can use.

**Comment by rsumit123** [comment]
@Shubhamrawat5 You can now use this url: https://cric-score.skdev.one/ permanently. Please use this now. I will be disabling the temp url shortly.

**Comment by Shubhamrawat5** [comment]
Yeah working great. Thanks

**Comment by Shubhamrawat5** [comment]
Not working currently. can you check

URL: 
https://testing-nine-theta.vercel.app/score?url=https://www.cricbuzz.com/live-cricket-scores/66404

Response:
"Something Went Wrong - Enter the Correct API URL"
